// Export all services
export { authService } from './authService'
export { userService } from './userService'
export { departmentService } from './departmentService'
export { batchService } from './batchService'
export { subjectService } from './subjectService'
export { facultyService } from './facultyService'
export { facultyAssignmentService } from './facultyAssignmentService'
export { studentService } from './studentService'
export { courseOfferingService } from './courseOfferingService'
export { courseEnrollmentService } from './courseEnrollmentService'
export { studentMarkService } from './studentMarkService'
export { attendanceService } from './attendanceService'
export { evaluationSchemeService, assessmentItemService } from './evaluationService'
export { dashboardService } from './dashboardService'
export { default as predictionService } from './predictionService'
export { default as uploadHistoryService } from './uploadHistoryService'
export { default as auditLogService } from './auditLogService'
export { default as api } from './api'
