// <auto-generated />
using System;
using GradeSense.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradeSense.API.Migrations
{
    [DbContext(typeof(GradeSenseDbContext))]
    [Migration("20260116131953_AddUserPhoneAndMultipleEmails")]
    partial class AddUserPhoneAndMultipleEmails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GradeSense.API.Models.AssessmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Raw");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("EvaluationSchemeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MaxMarks")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int?>("SubjectUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EvaluationSchemeId");

                    b.HasIndex("SubjectUnitId");

                    b.ToTable("AssessmentItems", t =>
                        {
                            t.HasCheckConstraint("CK_AssessmentItems_CalculationType", "[CalculationType] IN ('Raw', 'Average', 'BestOf')");
                        });
                });

            modelBuilder.Entity("GradeSense.API.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int?>("RecordedBy")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("RecordedBy");

                    b.ToTable("AttendanceRecords", t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceRecords_Status", "[Status] IN ('Present', 'Absent', 'Excused', 'Late')");
                        });
                });

            modelBuilder.Entity("GradeSense.API.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedFields")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("NewValue")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("OldValue")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Reason")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("GradeSense.API.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<int?>("ClassCoordinatorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Division")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassCoordinatorId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("GradeSense.API.Models.CourseEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AttendancePercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("CourseOfferingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Grade")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal?>("GradePoints")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("RollNumber")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "CourseOfferingId", "RollNumber" }, "UQ__CourseEn__C101C94234A927E2")
                        .IsUnique()
                        .HasFilter("[RollNumber] IS NOT NULL");

                    b.ToTable("CourseEnrollments", t =>
                        {
                            t.HasCheckConstraint("CK_CourseEnrollments_GradePoints", "[GradePoints] IS NULL OR [GradePoints] BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_CourseEnrollments_Status", "[Status] IN ('Active', 'Completed', 'Dropped', 'Withdrawn')");
                        });
                });

            modelBuilder.Entity("GradeSense.API.Models.CourseOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxEnrollment")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("SubjectCoordinatorId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("SubjectCoordinatorId");

                    b.HasIndex("SubjectId");

                    b.ToTable("CourseOfferings");
                });

            modelBuilder.Entity("GradeSense.API.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HoduserId")
                        .HasColumnType("int")
                        .HasColumnName("HODUserId");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HoduserId");

                    b.HasIndex(new[] { "Name" }, "UQ__Departme__737584F6CB232671")
                        .IsUnique();

                    b.HasIndex(new[] { "Code" }, "UQ__Departme__A25C5AA7288A8A0F")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("GradeSense.API.Models.EvaluationScheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseOfferingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("EvaluationType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PassingMarks")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal>("TotalMarks")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId");

                    b.ToTable("EvaluationSchemes");
                });

            modelBuilder.Entity("GradeSense.API.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("Qualification")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "EmployeeId" }, "UQ__Facultie__7AD04F107CF23582")
                        .IsUnique();

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("GradeSense.API.Models.FacultyAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("CourseOfferingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId");

                    b.HasIndex("FacultyId");

                    b.ToTable("FacultyAssignments");
                });

            modelBuilder.Entity("GradeSense.API.Models.Prediction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<int>("CourseEnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExplanationJson")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FeatureImportance")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("ModelAccuracy")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PredictedCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PredictedGrade")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal?>("PredictedMarks")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("RecommendedActions")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ReviewNotes")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseEnrollmentId");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("Predictions", t =>
                        {
                            t.HasCheckConstraint("CK_Predictions_Category", "[PredictedCategory] IN ('At-Risk', 'Safe', 'High-Achiever', 'Needs-Attention')");

                            t.HasCheckConstraint("CK_Predictions_ConfidenceScore", "[ConfidenceScore] IS NULL OR ([ConfidenceScore] >= 0 AND [ConfidenceScore] <= 1)");

                            t.HasCheckConstraint("CK_Predictions_RiskScore", "[RiskScore] >= 0 AND [RiskScore] <= 1");
                        });
                });

            modelBuilder.Entity("GradeSense.API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cgpa")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EnrollmentNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DepartmentId" }, "idx_students_department");

                    b.HasIndex(new[] { "EnrollmentNumber" }, "idx_students_enrollment")
                        .IsUnique();

                    b.HasIndex(new[] { "AdmissionYear", "CurrentSemester" }, "idx_students_year_sem");

                    b.ToTable("Students", t =>
                        {
                            t.HasCheckConstraint("CK_Students_CGPA", "[CGPA] BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_Students_Status", "[Status] IN ('Active', 'Suspended', 'Graduated', 'Dropped')");
                        });
                });

            modelBuilder.Entity("GradeSense.API.Models.StudentMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GradedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GraderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAbsent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("ObtainedMarks")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Remarks")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentItemId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("GraderId");

                    b.ToTable("StudentMarks", t =>
                        {
                            t.HasCheckConstraint("CK_StudentMarks_ObtainedMarks", "[ObtainedMarks] IS NULL OR [IsAbsent] = 0");
                        });
                });

            modelBuilder.Entity("GradeSense.API.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsElective")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PrerequisiteSubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Syllabus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PrerequisiteSubjectId");

                    b.HasIndex(new[] { "Code" }, "UQ__Subjects__A25C5AA70FD74FB3")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("GradeSense.API.Models.SubjectUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("LearningOutcomes")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeachingHours")
                        .HasColumnType("int");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weightage")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectUnits");
                });

            modelBuilder.Entity("GradeSense.API.Models.UploadHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)");

                    b.Property<int?>("AssessmentItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseOfferingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ErrorDetails")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("RowDataBlob")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Processing");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentItemId");

                    b.HasIndex("CourseOfferingId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("UploadHistory", t =>
                        {
                            t.HasCheckConstraint("CK_UploadHistory_Status", "[Status] IN ('Processing', 'Completed', 'Failed')");
                        });
                });

            modelBuilder.Entity("GradeSense.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("InstitutionalEmail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionalEmail")
                        .IsUnique()
                        .HasFilter("[InstitutionalEmail] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex(new[] { "IsActive" }, "idx_users_active");

                    b.HasIndex(new[] { "InstitutionalEmail" }, "idx_users_institutional_email")
                        .IsUnique()
                        .HasFilter("[InstitutionalEmail] IS NOT NULL");

                    b.HasIndex(new[] { "PersonalEmail" }, "idx_users_personal_email")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "idx_users_phone")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex(new[] { "Role" }, "idx_users_role");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Student', 'Faculty', 'Admin')");
                        });
                });

            modelBuilder.Entity("GradeSense.API.Models.AssessmentItem", b =>
                {
                    b.HasOne("GradeSense.API.Models.Faculty", "CreatedByNavigation")
                        .WithMany("AssessmentItems")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Assessmen__Creat__2FCF1A8A");

                    b.HasOne("GradeSense.API.Models.EvaluationScheme", "EvaluationScheme")
                        .WithMany("AssessmentItems")
                        .HasForeignKey("EvaluationSchemeId")
                        .IsRequired()
                        .HasConstraintName("FK__Assessmen__Evalu__2DE6D218");

                    b.HasOne("GradeSense.API.Models.SubjectUnit", "SubjectUnit")
                        .WithMany("AssessmentItems")
                        .HasForeignKey("SubjectUnitId")
                        .HasConstraintName("FK__Assessmen__Subje__2EDAF651");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("EvaluationScheme");

                    b.Navigation("SubjectUnit");
                });

            modelBuilder.Entity("GradeSense.API.Models.AttendanceRecord", b =>
                {
                    b.HasOne("GradeSense.API.Models.CourseEnrollment", "Enrollment")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Attendanc__Enrol__3587F3E0");

                    b.HasOne("GradeSense.API.Models.Faculty", "RecordedByNavigation")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("RecordedBy")
                        .HasConstraintName("FK__Attendanc__Recor__367C1819");

                    b.Navigation("Enrollment");

                    b.Navigation("RecordedByNavigation");
                });

            modelBuilder.Entity("GradeSense.API.Models.AuditLog", b =>
                {
                    b.HasOne("GradeSense.API.Models.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .IsRequired()
                        .HasConstraintName("FK__AuditLog__ActorU__3A4CA8FD");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("GradeSense.API.Models.Batch", b =>
                {
                    b.HasOne("GradeSense.API.Models.Faculty", "ClassCoordinator")
                        .WithMany("Batches")
                        .HasForeignKey("ClassCoordinatorId")
                        .HasConstraintName("FK__Batches__ClassCo__245D67DE");

                    b.HasOne("GradeSense.API.Models.Department", "Department")
                        .WithMany("Batches")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Batches__Departm__236943A5");

                    b.Navigation("ClassCoordinator");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GradeSense.API.Models.CourseEnrollment", b =>
                {
                    b.HasOne("GradeSense.API.Models.CourseOffering", "CourseOffering")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("CourseOfferingId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseEnr__Cours__2B0A656D");

                    b.HasOne("GradeSense.API.Models.Student", "Student")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseEnr__Stude__2BFE89A6");

                    b.Navigation("CourseOffering");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GradeSense.API.Models.CourseOffering", b =>
                {
                    b.HasOne("GradeSense.API.Models.Batch", "Batch")
                        .WithMany("CourseOfferings")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseOff__Batch__29221CFB");

                    b.HasOne("GradeSense.API.Models.Faculty", "SubjectCoordinator")
                        .WithMany("CourseOfferings")
                        .HasForeignKey("SubjectCoordinatorId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseOff__Subje__2A164134");

                    b.HasOne("GradeSense.API.Models.Subject", "Subject")
                        .WithMany("CourseOfferings")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseOff__Subje__282DF8C2");

                    b.Navigation("Batch");

                    b.Navigation("Subject");

                    b.Navigation("SubjectCoordinator");
                });

            modelBuilder.Entity("GradeSense.API.Models.Department", b =>
                {
                    b.HasOne("GradeSense.API.Models.User", "Hoduser")
                        .WithMany("Departments")
                        .HasForeignKey("HoduserId")
                        .HasConstraintName("FK__Departmen__HODUs__1EA48E88");

                    b.Navigation("Hoduser");
                });

            modelBuilder.Entity("GradeSense.API.Models.EvaluationScheme", b =>
                {
                    b.HasOne("GradeSense.API.Models.CourseOffering", "CourseOffering")
                        .WithMany("EvaluationSchemes")
                        .HasForeignKey("CourseOfferingId")
                        .IsRequired()
                        .HasConstraintName("FK__Evaluatio__Cours__2CF2ADDF");

                    b.Navigation("CourseOffering");
                });

            modelBuilder.Entity("GradeSense.API.Models.Faculty", b =>
                {
                    b.HasOne("GradeSense.API.Models.Department", "Department")
                        .WithMany("Faculties")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Faculties__Depar__208CD6FA");

                    b.HasOne("GradeSense.API.Models.User", "IdNavigation")
                        .WithOne("Faculty")
                        .HasForeignKey("GradeSense.API.Models.Faculty", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__Faculties__Id__1F98B2C1");

                    b.Navigation("Department");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("GradeSense.API.Models.FacultyAssignment", b =>
                {
                    b.HasOne("GradeSense.API.Models.CourseOffering", "CourseOffering")
                        .WithMany("FacultyAssignments")
                        .HasForeignKey("CourseOfferingId")
                        .IsRequired()
                        .HasConstraintName("FK__FacultyAs__Cours__339FAB6E");

                    b.HasOne("GradeSense.API.Models.Faculty", "Faculty")
                        .WithMany("FacultyAssignments")
                        .HasForeignKey("FacultyId")
                        .IsRequired()
                        .HasConstraintName("FK__FacultyAs__Facul__3493CFA7");

                    b.Navigation("CourseOffering");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("GradeSense.API.Models.Prediction", b =>
                {
                    b.HasOne("GradeSense.API.Models.CourseEnrollment", "CourseEnrollment")
                        .WithMany("Predictions")
                        .HasForeignKey("CourseEnrollmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Predictio__Cours__3B40CD36");

                    b.HasOne("GradeSense.API.Models.Faculty", "ReviewedByNavigation")
                        .WithMany("Predictions")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("FK__Predictio__Revie__3C34F16F");

                    b.Navigation("CourseEnrollment");

                    b.Navigation("ReviewedByNavigation");
                });

            modelBuilder.Entity("GradeSense.API.Models.Student", b =>
                {
                    b.HasOne("GradeSense.API.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Students__Depart__22751F6C");

                    b.HasOne("GradeSense.API.Models.User", "IdNavigation")
                        .WithOne("Student")
                        .HasForeignKey("GradeSense.API.Models.Student", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__Students__Id__2180FB33");

                    b.Navigation("Department");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("GradeSense.API.Models.StudentMark", b =>
                {
                    b.HasOne("GradeSense.API.Models.AssessmentItem", "AssessmentItem")
                        .WithMany("StudentMarks")
                        .HasForeignKey("AssessmentItemId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentMa__Asses__31B762FC");

                    b.HasOne("GradeSense.API.Models.CourseEnrollment", "Enrollment")
                        .WithMany("StudentMarks")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentMa__Enrol__30C33EC3");

                    b.HasOne("GradeSense.API.Models.Faculty", "Grader")
                        .WithMany("StudentMarks")
                        .HasForeignKey("GraderId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentMa__Grade__32AB8735");

                    b.Navigation("AssessmentItem");

                    b.Navigation("Enrollment");

                    b.Navigation("Grader");
                });

            modelBuilder.Entity("GradeSense.API.Models.Subject", b =>
                {
                    b.HasOne("GradeSense.API.Models.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Subjects__Depart__25518C17");

                    b.HasOne("GradeSense.API.Models.Subject", "PrerequisiteSubject")
                        .WithMany("InversePrerequisiteSubject")
                        .HasForeignKey("PrerequisiteSubjectId")
                        .HasConstraintName("FK__Subjects__Prereq__2645B050");

                    b.Navigation("Department");

                    b.Navigation("PrerequisiteSubject");
                });

            modelBuilder.Entity("GradeSense.API.Models.SubjectUnit", b =>
                {
                    b.HasOne("GradeSense.API.Models.Subject", "Subject")
                        .WithMany("SubjectUnits")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__SubjectUn__Subje__2739D489");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("GradeSense.API.Models.UploadHistory", b =>
                {
                    b.HasOne("GradeSense.API.Models.AssessmentItem", "AssessmentItem")
                        .WithMany("UploadHistories")
                        .HasForeignKey("AssessmentItemId")
                        .HasConstraintName("FK__UploadHis__Asses__3864608B");

                    b.HasOne("GradeSense.API.Models.CourseOffering", "CourseOffering")
                        .WithMany("UploadHistories")
                        .HasForeignKey("CourseOfferingId")
                        .IsRequired()
                        .HasConstraintName("FK__UploadHis__Cours__37703C52");

                    b.HasOne("GradeSense.API.Models.Faculty", "UploadedByNavigation")
                        .WithMany("UploadHistories")
                        .HasForeignKey("UploadedBy")
                        .IsRequired()
                        .HasConstraintName("FK__UploadHis__Uploa__395884C4");

                    b.Navigation("AssessmentItem");

                    b.Navigation("CourseOffering");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("GradeSense.API.Models.AssessmentItem", b =>
                {
                    b.Navigation("StudentMarks");

                    b.Navigation("UploadHistories");
                });

            modelBuilder.Entity("GradeSense.API.Models.Batch", b =>
                {
                    b.Navigation("CourseOfferings");
                });

            modelBuilder.Entity("GradeSense.API.Models.CourseEnrollment", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Predictions");

                    b.Navigation("StudentMarks");
                });

            modelBuilder.Entity("GradeSense.API.Models.CourseOffering", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("EvaluationSchemes");

                    b.Navigation("FacultyAssignments");

                    b.Navigation("UploadHistories");
                });

            modelBuilder.Entity("GradeSense.API.Models.Department", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Faculties");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("GradeSense.API.Models.EvaluationScheme", b =>
                {
                    b.Navigation("AssessmentItems");
                });

            modelBuilder.Entity("GradeSense.API.Models.Faculty", b =>
                {
                    b.Navigation("AssessmentItems");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("Batches");

                    b.Navigation("CourseOfferings");

                    b.Navigation("FacultyAssignments");

                    b.Navigation("Predictions");

                    b.Navigation("StudentMarks");

                    b.Navigation("UploadHistories");
                });

            modelBuilder.Entity("GradeSense.API.Models.Student", b =>
                {
                    b.Navigation("CourseEnrollments");
                });

            modelBuilder.Entity("GradeSense.API.Models.Subject", b =>
                {
                    b.Navigation("CourseOfferings");

                    b.Navigation("InversePrerequisiteSubject");

                    b.Navigation("SubjectUnits");
                });

            modelBuilder.Entity("GradeSense.API.Models.SubjectUnit", b =>
                {
                    b.Navigation("AssessmentItems");
                });

            modelBuilder.Entity("GradeSense.API.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Departments");

                    b.Navigation("Faculty");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
